### ISSUE TITLE
[4th Ed] the schemas overall would benefit from common entity and datatypes

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/DASHSchema#83]
As the list of schema files grows (as well as reuse of typing within a schema), it would be good to introduce more structure to the typing with the use of entity and more common XML typing.

**Comment by paulhiggs** [comment]
Several options are possible
1. create a new "base types" schema with all the datatypes that will be used in multiple schemas - this may or may not include all ENTITY definitions
2.  create `DASH-entities.dtd` and "include" it into the schemas with `<!DOCTYPE root-element SYSTEM "../DASH-entities.dtd">`
Any way, we should have ci scripts wo validate patterns and definitions against known good examples, i.e.

@profiles-validation.xsd
````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root-element SYSTEM "../DASH-entities.dtd">
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Tests">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="profiles">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="(&URN;|&URL;)(,(&URN;|&URL;))*"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element> 
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>
```` 

@profiles-validation.xml
````
<?xml version="1.0" encoding="UTF-8"?>
<Tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="@profiles-validation.xsd">
	<profiles>urn:mpeg:dash:profile:isoff-on-demand:2011,http://dashif.org/guidelines/dash264</profiles>
	<profiles>sss:ee:r</profiles>
	<profiles>http://dashif.org/guidelines/dash264</profiles>
	<profiles>http://paul@dashif.org/guidelines/dash264</profiles>
	<profiles>http://paul:higgs@dashif.org/guidelines/dash264</profiles>
	<profiles>http://pa*ul:higgs@dashif.org/guidelines/dash264/j.ds</profiles>
	<profiles>ftp://192.168.2.3:64/hosts?a=7&amp;b=87</profiles>
	<profiles>urn:mpeg:dash:profile:isoff-on-demand:20?~11</profiles>
</Tests>
````

In this way, changes to DTD-entities.xsd will be validated syntactically and semantically against the (xsd, xml) combinations

**Comment by paulhiggs** [comment]
Any preference between

1. define a base types schema that can be imported into the main DASH schema and any additional schemas
2. define entities that can be included in the main DASH schema an any additional schemas (note that if a data type defined in DASH-MPD.xsd is needed in the additional schema then it can be imported)

**Comment by mikedo** [comment]
Wouldn't 1 be both entities and types?  Offhand that might be the most flexible.

**Comment by paulhiggs** [comment]
> Wouldn't 1 be both entities and types? Offhand that might be the most flexible.

Yes, but I currently have the DTD and base types separated since I use the DTD alone in validation tests. You can see this in my 5th edition fork - https://github.com/paulhiggs/DASHSchema

**Comment by paulhiggs** [comment]
We will need to look at the ci if we use DTD ENTITY.

I did a test in my fork and get errors
````
Traceback (most recent call last):
  File "/home/runner/work/DASHSchema/DASHSchema/tests/validate.py", line 26, in test_mpds
    self.mpd_schema.assertValid(mpd)
  File "src/lxml/etree.pyx", line 3623, in lxml.etree._Validator.assertValid
lxml.etree.DocumentInvalid: Element '{urn:mpeg:dash:schema:mpd:2011}MPD', attribute 'profiles': [facet 'pattern'] The value 'urn:mpeg:dash:profile:isoff-live:2011' is not accepted by the pattern '(|)(,(|))*'., line 12
````

The `pattern '(|)(,(|))*' does not seem to bring in &URN; and &URL; from DASH-entities.dtd

**Comment by paulhiggs** [comment]
> We will need to look at the ci if we use DTD ENTITY.
> 
> I did a test in my fork and get errors
> 
> ```
> Traceback (most recent call last):
>   File "/home/runner/work/DASHSchema/DASHSchema/tests/validate.py", line 26, in test_mpds
>     self.mpd_schema.assertValid(mpd)
>   File "src/lxml/etree.pyx", line 3623, in lxml.etree._Validator.assertValid
> lxml.etree.DocumentInvalid: Element '{urn:mpeg:dash:schema:mpd:2011}MPD', attribute 'profiles': [facet 'pattern'] The value 'urn:mpeg:dash:profile:isoff-live:2011' is not accepted by the pattern '(|)(,(|))*'., line 12
> ```
> 
> The `pattern '(|)(,(|))*` does not seem to bring in &URN; and &URL; from DASH-entities.dtd

This is the result of some bugs etc in libxml2 which is then pulled into the lxml python bindings. Should have this eesolved soon so that separate entity DTD  and types XSD can be created for unit testing and maintenance purposes.

One bug ([libxml2#242](https://gitlab.gnome.org/GNOME/libxml2/-/issues/242)) regarding xs:language is already solved - another ([libxml2#250](https://gitlab.gnome.org/GNOME/libxml2/-/issues/250)) relating to depth/size of entities is currently in progress

**Comment by ZmGorynych** [comment]
Is the issue still relevant?

**Comment by paulhiggs** [comment]
The idea of this was to split some definitions into a separate includable XSD - but its probably not needed as we put everything into the main DASH schema.
